export const environment = {
    apiKey: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNjJlMGM5Yjk3MjEzODY2MTM2ZGQxZTRlNjBkYzU2NSIsIm5iZiI6MTc0NTY3MjQwNC41NTcsInN1YiI6IjY4MGNkOGQ0MTYzNWQyOTE4YzgwZDkxYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.h6ngYKNEil9E6hump3b1mWlzSmuSdgQWKEFOz6IBOEI",
    production: false   
}